rootPageId: 1
base: '%env(SITE_MAIN_BASE)%'
baseVariants: {  }
languages:
  -
    title: English
    enabled: true
    languageId: '0'
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: global
errorHandling: {  }
routes: {  }
